#!/bin/bash
# Change the following values to suit your local setup.
# Add this file to your .git/hooks/ and name it as 'pre-commit'
#

# The path relative to the repository root in which to store the SQL dump.
FILE_PATH="suivi/commitinfo.txt"

# Prompt the user for confirmation
read -p "Sauvegarde de la base dans ce commit (y/[n]) ? " yn < /dev/tty

# Default to 'n' if no input is given
yn=${yn:-n}

# Check the user's input and take action
case $yn in
    [Yy]* )
        # Get the current date and time
        date_time=$(date)
        # Append the date and time to the specified file
        echo -e "\nCommit verifié le: $date_time" >> "$FILE_PATH"
        git add "$FILE_PATH"
        ;;
    [Nn]* )
        exit 0
        ;;
    * )
        echo "Invalid input. Please enter y or n."
        exit 1
        ;;
esac

exit 0